### ISSUE TITLE
마크다운 코드블록 스타일 커스텀

### ISSUE THREAD

**Issue by overtae** [overtae/tae-log#3]
### TODO

- [x] 언어 이름 표시
- [ ] 코드 복사 버튼 추가
- [x] (선택) 코드 줄 번호 표시
- [x] (선택) 코드 줄 별 하이라이팅 기능 추가

### 참고

- [rehype-pretty-code](https://github.com/rehype-pretty/rehype-pretty-code)
- [rehype-pretty-code themes](https://rehype-pretty-example-next.pages.dev/)

### 목표 디자인

![image](https://github.com/user-attachments/assets/09d2b72b-b3c8-4349-8fc2-8a1430b407fd)

**Comment by overtae** [comment]
> [!NOTE]
> https://github.com/rehype-pretty/rehype-pretty-code/issues/208

- 현재 rehype-pretty의 copy 버튼을 사용하려면 client 컴포넌트에서 가능
- 다른 방법을 알아보거나 copy 버튼은 추후에 추가하기
